github.com:
    git_protocol: https
    users:
        DNM1008:
            oauth_token: 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
    user: DNM1008
    oauth_token: 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
