device_name = "AT Translated Set 2 keyboard"

[[remap]]

input = ["KEY_CAPSLOCK"]
output = ["KEY_TAB"]
[[remap]]
input = ["KEY_LEFTALT", "KEY_UP"]
output = ["KEY_PAGEUP"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_DOWN"]
output = ["KEY_PAGEDOWN"]

[[remap]]

input = ["KEY_TAB"]
output = ["KEY_ESC"]

[[remap]]

input = ["KEY_ESC"]
output = ["KEY_CAPSLOCK"]

[[remap]]

input = ['KEY_PAGEUP']
output = ['KEY_BACK']

[[remap]]

input = ['KEY_PAGEDOWN']
output = ['KEY_FORWARD']

[[remap]]

input = ['KEY_PRINT']
output = ['KEY_R']
