- 1.1.14
- _NAME: Wireless Mobile Mouse MX Anywhere 2S
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended,
    pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered,
    backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer,
    adc_power_management]
  _battery: 4096
  _modelId: B01A406A0000
  _sensitive: {change-host: true, divert-keys: true, dpi: true, hires-smooth-invert: true, hires-smooth-resolution: true, reprogrammable-keys: true}
  _unitId: 7D75541F
  change-host: null
  divert-keys: {82: 2, 83: 0, 86: 0, 91: 0, 93: 3}
  dpi: 500
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 81, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 215}
