# Only set DISPLAY if in X11 session
if [ "$XDG_SESSION_TYPE" = "x11" ]; then
  export DISPLAY=:0
fi
export INIT_X11_SCALE_FACTOR=1.5
# ~/.bash_profile


# XDG stuff
WINIT_HIDPI_FACTOR=1.0
[[ -f ~/.config/bash/bashrc ]] && . ~/.config/bash/bashrc
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

# Cleaning home
cache=${XDG_CACHE_HOME}/npm
export ANDROID_HOME="$XDG_DATA_HOME"/android
export BROWSER='firefox'
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export EDITOR='nvim'
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc:$XDG_CONFIG_HOME/gtk-2.0/gtkrc.mine"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export PATH="$PATH:/opt/nvim-linux64/bin"
export PERL_DESTRUCT_LEVEL=2
export HISTFILE="${XDG_STATE_HOME}"/bash/history      
export LS_COLORS='tw=00;33:ow=01;33:'
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export NO_AT_BRIDGE=1
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export OLLAMA_MODELS=$XDG_DATA_HOME/ollama/models
export PATH="$HOME/.local/bin/:$PATH"		
export PATH="$HOME/.local/bin/miniconda3/:$PATH"		
export PATH="$HOME/.local/bin/scripts:$PATH"		
export PATH="$HOME/.local/share/python/bin:$PATH"		
export PATH="/usr/bin:$PATH"
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
export RANGER_LOAD_DEFAULT_RC=FALSE
export TERM='xterm-kitty'
export TERMINAL='kitty'
export EDITOR='nvim'
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
export TEXMHOME=$XDG_DATA_HOME/texmf
# export XAUTHORITY=$XDG_RUNTIME_DIR/lyauth
export XCURSOR_PATH=/usr/share/icons:$XDG_DATA_HOME/icons  
export PYTHON_HISTORY=$XDG_STATE_HOME/python/history
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python
export npm_config_cache="${XDG_CACHE_HOME}/npm"
prefix=${XDG_DATA_HOME}/npm
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
export TESSDATA_PREFIX="/usr/share"
export NLTK_DATA=/usr/share/nltk_data
export REDISCLI_HISTFILE="$XDG_DATA_HOME"/redis/rediscli_history
export VALKEYCLI_HISTFILE="$XDG_DATA_HOME"/valkey/valkeycli_history
export QT_QPA_PLATFORM="xcb"
