# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

shopt -s autocd
HISTSIZE= HISTFILESIZE=

# aliases
alias homecount='ls ~ -lA | wc -l'
alias grep='grep --color=auto'
alias ls='eza --color=auto --icons=always -l'
alias shutnow='shutdown now'
alias adb='HOME="$XDG_DATA_HOME"/android adb'
alias vim='nvim'
alias sudo='sudo '
alias lf='lfub'

#PS1='[\u@\h \W]\$ '

# Pretty (?) neofetch and a quote to start
neofetch && echo && fortune && echo

# Case insensitive tab autocomplete
bind -s 'set completion-ignore-case on'

eval "$(starship init bash)"	# Starship prompt
if [[ -r /usr/share/bash-completion/bash_completion ]]; then
  . /usr/share/bash-completion/bash_completion		# Enable auto complete
fi

cl() {
	local dir="$1"
	local dir="${dir:=$HOME}"
	if [[ -d "$dir" ]]; then
		cd "$dir" >/dev/null; ls
	else
		echo "bash: cl: $dir: Directory not found"
	fi
}

PERL_DESTRUCT_LEVEL=2


eval "$(antidot init)"
