
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 11

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Medium"

[window]
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 12 
y = 6

[general]
import = ["/home/zeus/.config/alacritty/catppuccin-macchiato.toml"]
