
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR= "1"

[font]
size = 9.5
normal = { family = "Fira Mono", style = "Medium"}
italic = {style = "Italic"}
bold = {style = "bold"}

[window]
opacity= 0.95
dynamic_padding=true
padding={x=10, y=0}

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
